# -*- coding: utf-8 -*-
"""SS-coloring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bo17lvSzFUgbMfJU1xsoOYVOiztmblLX
"""

import altair as alt
import pandas as pd

res = pd.read_csv("colors",skiprows=[0])

import altair as alt


chart = alt.Chart(res).mark_circle(size = 60).encode(
    x='ParticleX',
    y='ParticleY',
    color=alt.Color('ParticleType', type='nominal'),
).properties(
    width=600,
    height=600
)

chart.save('chart.svg')